"""
HTML report generator for VulnPatch.

Generates professional HTML-format audit reports from AuditResult objects.
"""

from __future__ import annotations

from audit_core.models import AuditResult


def build_html_report(result: AuditResult) -> str:
    """
    Build an HTML audit report from an AuditResult.

    Args:
        result: The audit result to convert.

    Returns:
        HTML string.
    """
    s = result.summary
    risk_color = "#f56c6c" if s.risk_score >= 70 else "#e6a23c" if s.risk_score >= 40 else "#67c23a"

    # 构建发现行
    finding_rows = ""
    for i, f in enumerate(result.findings, 1):
        sev_color = {"ERROR": "#f56c6c", "WARN": "#e6a23c", "INFO": "#409eff"}.get(f.severity.upper(), "#909399")
        snippet_html = ""
        for e in result.evidence:
            if e.finding.id == f.id and e.snippets:
                for snippet in e.snippets:
                    content = snippet if isinstance(snippet, str) else str(snippet)
                    snippet_html += f'<pre style="background:#1e1e1e;color:#d4d4d4;padding:12px;border-radius:6px;overflow-x:auto;font-size:13px;"><code>{_esc(content)}</code></pre>'

        judge_html = ""
        for e in result.evidence:
            if e.finding.id == f.id and e.judge_decision:
                jd = e.judge_decision
                judge_html = f'<p><strong>Judge Verdict:</strong> {jd.verdict} | <strong>Risk:</strong> {jd.risk_score} | <strong>Reason:</strong> {_esc(jd.reason)}</p>'

        finding_rows += f"""
        <div style="border:1px solid #e4e7ed;border-radius:8px;padding:16px;margin:12px 0;">
          <h4 style="margin:0 0 8px;">{i}. {f.type}</h4>
          <p style="margin:4px 0;"><strong>File:</strong> <code>{_esc(f.file_path)}</code> | <strong>Line:</strong> {f.start_line} | <strong>Severity:</strong> <span style="color:{sev_color};font-weight:bold;">{f.severity}</span> | <strong>CWE:</strong> {f.cwe or '-'}</p>
          <p style="margin:4px 0;"><strong>Message:</strong> {_esc(f.message)}</p>
          <p style="margin:4px 0;"><strong>Engine:</strong> {f.engine} | <strong>Confidence:</strong> {f.confidence}</p>
          {judge_html}
          {snippet_html}
        </div>"""

    # Agent 日志行
    log_rows = ""
    for log in result.agent_logs:
        log_rows += f'<tr><td>{log.agent_name}</td><td>{log.stage}</td><td>{_esc(log.message)}</td></tr>'

    # 扫描文件列表
    files_html = ""
    for fp in s.scanned_files[:20]:
        files_html += f'<code style="margin:2px;padding:2px 6px;background:#f4f4f4;border-radius:3px;">{_esc(fp)}</code> '

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VulnPatch Audit Report</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 1000px; margin: 0 auto; padding: 24px; color: #303133; }}
    h1 {{ color: #303133; border-bottom: 2px solid #409eff; padding-bottom: 8px; }}
    h2 {{ color: #409eff; margin-top: 32px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
    th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
    th {{ background: #f5f7fa; }}
    .kpi {{ display: flex; gap: 16px; flex-wrap: wrap; margin: 16px 0; }}
    .kpi-card {{ background: #f5f7fa; border-radius: 8px; padding: 16px 24px; min-width: 140px; text-align: center; }}
    .kpi-value {{ font-size: 28px; font-weight: 700; }}
    .kpi-label {{ font-size: 13px; color: #909399; margin-top: 4px; }}
  </style>
</head>
<body>
  <h1>VulnPatch Audit Report</h1>
  <p><em>Generated by VulnPatch - 自主多模型调度与案例库自进化的漏洞修复辅助系统</em></p>

  <h2>Summary</h2>
  <div class="kpi">
    <div class="kpi-card"><div class="kpi-value">{s.total_code_units}</div><div class="kpi-label">Code Units</div></div>
    <div class="kpi-card"><div class="kpi-value" style="color:{risk_color}">{s.risk_score:.1f}</div><div class="kpi-label">Risk Score</div></div>
    <div class="kpi-card"><div class="kpi-value">{s.total_findings}</div><div class="kpi-label">Findings</div></div>
    <div class="kpi-card"><div class="kpi-value">{s.total_evidence_bundles}</div><div class="kpi-label">Evidence</div></div>
  </div>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Languages</td><td>{', '.join(s.languages) if s.languages else 'N/A'}</td></tr>
    <tr><td>Scanned Files</td><td>{len(s.scanned_files)}</td></tr>
  </table>

  <h2>Findings</h2>
  {finding_rows if finding_rows else '<p>No vulnerabilities found.</p>'}

  <h2>Agent Logs</h2>
  <table>
    <tr><th>Agent</th><th>Stage</th><th>Message</th></tr>
    {log_rows if log_rows else '<tr><td colspan="3">No logs available.</td></tr>'}
  </table>

  <h2>Scanned Files</h2>
  <div>{files_html if files_html else 'N/A'}</div>

  <hr>
  <p style="text-align:center;color:#909399;font-size:12px;">VulPatch &copy; 2024 - AI Security Audit Platform</p>
</body>
</html>"""

    return html


def _esc(text: str) -> str:
    """HTML 转义"""
    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
