"""
Markdown report generator for VulnPatch.

Generates Markdown-format audit reports from AuditResult objects.
"""

from __future__ import annotations

from audit_core.models import AuditResult


def build_markdown_report(result: AuditResult) -> str:
    """
    Build a Markdown audit report from an AuditResult.

    Args:
        result: The audit result to convert.

    Returns:
        Markdown string.
    """
    lines: list[str] = []

    # 标题
    lines.append("# Audit Report")
    lines.append("")
    lines.append("> Generated by VulnPatch - AI 安全审计平台")
    lines.append("")

    # 摘要
    lines.append("## Summary")
    lines.append("")
    s = result.summary
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Code Units | {s.total_code_units} |")
    lines.append(f"| Findings | {s.total_findings} |")
    lines.append(f"| Evidence Bundles | {s.total_evidence_bundles} |")
    lines.append(f"| Risk Score | {s.risk_score:.1f}/100 |")
    lines.append(f"| Languages | {', '.join(s.languages) if s.languages else 'N/A'} |")
    lines.append(f"| Scanned Files | {len(s.scanned_files)} |")
    lines.append("")

    # 漏洞发现
    lines.append("## Findings")
    lines.append("")
    if result.findings:
        lines.append("| # | Type | Severity | Confidence | File | Line | CWE |")
        lines.append("|---|------|----------|------------|------|------|-----|")
        for i, f in enumerate(result.findings, 1):
            cwe = f.cwe or "-"
            lines.append(
                f"| {i} | {f.type} | {f.severity} | {f.confidence} | "
                f"`{f.file_path}` | {f.start_line} | {cwe} |"
            )
        lines.append("")

        # 详细信息
        lines.append("### Finding Details")
        lines.append("")
        for i, f in enumerate(result.findings, 1):
            lines.append(f"#### {i}. {f.type}")
            lines.append("")
            lines.append(f"- **Rule ID**: {f.rule_id}")
            lines.append(f"- **Severity**: {f.severity}")
            lines.append(f"- **Confidence**: {f.confidence}")
            lines.append(f"- **File**: `{f.file_path}`")
            lines.append(f"- **Line**: {f.start_line}" + (f"-{f.end_line}" if f.end_line else ""))
            if f.cwe:
                lines.append(f"- **CWE**: {f.cwe}")
            lines.append(f"- **Engine**: {f.engine}")
            lines.append(f"- **Message**: {f.message}")
            lines.append("")

            # 代码片段
            for e in result.evidence:
                if e.finding.id == f.id and e.snippets:
                    lines.append("**Code Snippet:**")
                    lines.append("```")
                    for snippet in e.snippets:
                        if isinstance(snippet, str):
                            lines.append(snippet)
                        elif isinstance(snippet, dict) and "content" in snippet:
                            lines.append(snippet["content"])
                    lines.append("```")
                    lines.append("")

            # 裁决
            for e in result.evidence:
                if e.finding.id == f.id and e.judge_decision:
                    jd = e.judge_decision
                    lines.append(f"**Judge Verdict**: {jd.verdict} (confidence: {jd.confidence}, risk: {jd.risk_score})")
                    lines.append(f"**Reason**: {jd.reason}")
                    lines.append("")
    else:
        lines.append("No vulnerabilities found.")
        lines.append("")

    # Agent 日志
    lines.append("## Agent Logs")
    lines.append("")
    if result.agent_logs:
        lines.append("| Agent | Stage | Message |")
        lines.append("|-------|-------|---------|")
        for log in result.agent_logs:
            lines.append(f"| {log.agent_name} | {log.stage} | {log.message} |")
        lines.append("")
    else:
        lines.append("No agent logs available.")
        lines.append("")

    return "\n".join(lines)
